# Managed by https://github.com/linkorb/repo-ansible. Manual changes will be overwritten.
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blazon.serviceAccountName" . }}
  labels:
    {{- include "blazon.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
