name: BuildLatest

on:
  push:
    branches:
    - master
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v2

    - uses: actions/checkout@v2

    - name: Docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io --username automation@linkorb.com --password-stdin

    - name: Build the Docker image
      run: docker build . --build-arg PACKAGIST_USER="token" --build-arg PACKAGIST_TOKEN="${{secrets.PACKAGIST_TOKEN}}" --label "org.opencontainers.image.source=https://github.com/linkorb/${{ env.CI_REPOSITORY_NAME}}" --tag ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:latest --file Dockerfile

    - name: Docker push with latest tag
      run: docker push ghcr.io/linkorb/${{ env.CI_REPOSITORY_NAME }}:latest
